FROM composer:2 AS vendor

WORKDIR app

COPY . .

RUN composer config --global --no-interaction allow-plugins true

RUN composer install --no-dev --optimize-autoloader --no-interaction --no-scripts




FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

COPY . .

COPY --from=vendor /app/vendor ./vendor

RUN apt-get update && apt-get install -y unzip git curl

EXPOSE 8000

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
