FROM python:3.13-slim AS builder

WORKDIR app

COPY requirements.txt .

RUN pip install --prefix=/install --no-cache-dir -r requirements.txt


FROM python:3.13-alpine

WORKDIR app

COPY --from=builder /install /usr/local

COPY app app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
